### ISSUE TITLE
Patch for /trunk/src/freetuxtv-window-main.c

### ISSUE THREAD

**Issue by GoogleCodeExporter** [freetuxtv/freetuxtv#186]
```
Make string translatable
```

Original issue reported on code.google.com by `kockarjim@gmail.com` on 28 May 2014 at 9:33

Attachments:
* [freetuxtv-window-main.c.patch](https://storage.googleapis.com/google-code-attachments/freetuxtv/issue-186/comment-0/freetuxtv-window-main.c.patch)

**Comment by SaiyanRiku** [comment]
The string should be already translated by GTK.
