### ISSUE TITLE
Add TV channel Frikanalen?

### ISSUE THREAD

**Issue by petterreinholdtsen** [freetuxtv/freetuxtv#199]
Hi.  What is needed to add Frikanalen as a TV station in FreeTuxTV?  The channel is streamed on the web and can be seen on <URL: http://frikanalen.no/se >.

**Comment by SaiyanRiku** [comment]
Hi,

you can submit the link for the video stream (not the web page) here
http://database.freetuxtv.net/ (if vlc compatible)

2016-06-01 23:20 GMT+02:00 petterreinholdtsen <notifications@github.com>:

**Comment by petterreinholdtsen** [comment]
Hi.

[SaiyanRiku]
> you can submit the link for the video stream (not the web page) here
> http://database.freetuxtv.net/ (if vlc compatible)

Done.  The web stream is a WebM stream compatible with VLC.

Note, the schedule is available in XMLTV format from
<URL: http://beta.frikanalen.no/xmltv/ >.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
The Frikanalen entry is now in the database.  Closing this issue as fixed.
