### ISSUE TITLE
Fix build problem with gtk 2

### ISSUE THREAD

**Issue by petterreinholdtsen** [freetuxtv/freetuxtv#200]
Hi.

While brushing up the Debian package I discovered that the latest release did not build with Gtk 2 in Debian stable.  A fix for this is now available from http://anonscm.debian.org/cgit/pkg-multimedia/freetuxtv.git/tree/debian/patches/02_gtkv2_port.diff .

**Comment by SaiyanRiku** [comment]
Ok i will integrate the patch in upstream package
