### ISSUE TITLE
freetuxtv 0.6.6 crash on debian 8 and Mint 18

### ISSUE THREAD

**Issue by pcench** [freetuxtv/freetuxtv#208]
Hi, 
this is the output on 
uname -a
Linux debian8-host 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
 if I open freetux in terminal: 
___________________________________________________
...~$ freetuxtv
[FreetuxTV]    INFO       : Compiled with GTK3
[FreetuxTV]    INFO       : Compiled with LibVLC version 2.2.0
[FreetuxTV]    INFO       : Compiled with libnotify version 0.7.6
[FreetuxTV]    INFO       : Loading FreetuxTV 0.6.6
[FreetuxTV]    INFO       : Loading user interface from path /usr/share/freetuxtv/ui
[FreetuxTV]    INFO       : Initializing user interface
[GMMKeys]      INFO       : Initialize
[GMMKeys]      INFO       : Activating media player keys
[GMMKeys]      CRITICAL   : Unable to grab media player keys: Could not get owner of name 'org.gnome.SettingsDaemon': no such name
[FreetuxTV]    INFO       : Using user configuration dir: /home/christoph/.config/FreetuxTV
[FreetuxTV]    INFO       : DBSync open database
[DBEvolution]  INFO       : Starting database evolution
[DBEvolution]  INFO       : Current database version is 0.6.0.2
[FreetuxTV]    INFO       : DBSync close database
[FreetuxTV]    INFO       : Loading config file /home/christoph/.config/FreetuxTV/config.ini
[FreetuxTV]    INFO       : Cannot load config file
[FreetuxTV]    INFO       : Creating media player widget
[FreetuxTV]    INFO       : Initializing LibVLC instance
[LibVLC-Gtk]   INFO       : Using instance vlc with 3 options [--no-xlib --ignore-config --no-video-title-show]
[FreetuxTV]    INFO       : DBSync open database
[FreetuxTV]    MESSAGE    : Synchronizing the tv channels list
[FreetuxTV]    INFO       : Loading the list of channels
[FreetuxTV]    INFO       : Loading the list of recordings
[FreetuxTV]    INFO       : DBSync close database
[FreetuxTV]    INFO       : Showing the main window, hide splashscreen
[FreetuxTV]    INFO       : Loading GtkBuilder object "dialogaddgroup" from /usr/share/freetuxtv/ui/addchannelsgroups.glade

** (freetuxtv:30208): CRITICAL **: gtk_builder_window_get_top_window: assertion 'GTK_IS_WINDOW(pObject)' failed

(freetuxtv:30208): Gtk-CRITICAL **: gtk_window_set_transient_for: assertion 'GTK_IS_WINDOW (window)' failed

(freetuxtv:30208): Gtk-CRITICAL **: gtk_window_set_position: assertion 'GTK_IS_WINDOW (window)' failed

(freetuxtv:30208): Gtk-CRITICAL **: gtk_tree_view_get_selection: assertion 'GTK_IS_TREE_VIEW (tree_view)' failed

(freetuxtv:30208): Gtk-CRITICAL **: gtk_tree_selection_set_mode: assertion 'GTK_IS_TREE_SELECTION (selection)' failed

(freetuxtv:30208): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:30208): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:30208): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:30208): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:30208): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:30208): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:30208): Gtk-CRITICAL **: gtk_tree_store_clear: assertion 'GTK_IS_TREE_STORE (tree_store)' failed
Speicherzugriffsfehler ((memory access error))
___________________________________________________

nearly the same in Mint 18. If helpful, I can send the log as well. 
What should I do? What more info do you need?

best whishes,
Christoph

**Comment by muzena** [comment]
@pcench 
Try install from this repo, i have Mint 18
https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/multimedija

**Comment by pcench** [comment]
thanks muzena, that seems to work. At least it starts w/o crash. :-) So far for Mint 18; what about debian?

**Comment by SaiyanRiku** [comment]
This have been fixed in FreetuxTV 0.6.7 (see issue #189), it should be fixed in Debian Stretch, but the package have not been update in Jessie.
