### ISSUE TITLE
Linux Mint 18 crash on start up

### ISSUE THREAD

**Issue by rhexa** [freetuxtv/freetuxtv#210]
Hi this is the output of uname -a
Linux android-335670892342 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[FreetuxTV]    INFO       : Compiled with GTK3
[FreetuxTV]    INFO       : Compiled with LibVLC version 2.2.2
[FreetuxTV]    INFO       : Compiled with libnotify version 0.7.6
[FreetuxTV]    INFO       : Loading FreetuxTV 0.6.6
[FreetuxTV]    INFO       : Loading user interface from path /usr/local/share/freetuxtv/ui
[FreetuxTV]    INFO       : Initializing user interface
[GMMKeys]      INFO       : Initialize
[GMMKeys]      INFO       : Activating media player keys
[GMMKeys]      CRITICAL   : Unable to grab media player keys: Could not get owner of name 'org.gnome.SettingsDaemon': no such name
[FreetuxTV]    INFO       : Using user configuration dir: /home/hexator/.config/FreetuxTV
[FreetuxTV]    INFO       : Directory created: /home/hexator/.config/FreetuxTV
[FreetuxTV]    INFO       : DBSync open database
[DBEvolution]  INFO       : Starting database creation
[DBEvolution]  INFO       : Installing database version 0.1.0.1
[DBEvolution]  INFO       : Installing database version 0.5.0.1
[DBEvolution]  INFO       : Installing database version 0.5.1.1
[DBEvolution]  INFO       : Installing database version 0.5.1.2
[DBEvolution]  INFO       : Installing database version 0.6.0.1
[DBEvolution]  INFO       : Installing database version 0.6.0.2
[FreetuxTV]    INFO       : DBSync close database
[FreetuxTV]    INFO       : Loading config file /home/hexator/.config/FreetuxTV/config.ini
[FreetuxTV]    INFO       : Cannot load config file
[FreetuxTV]    INFO       : Creating media player widget
[FreetuxTV]    INFO       : Initializing LibVLC instance
[LibVLC-Gtk]   INFO       : Using instance vlc with 3 options [--no-xlib --ignore-config --no-video-title-show]
[FreetuxTV]    INFO       : DBSync open database
[FreetuxTV]    MESSAGE    : Synchronizing the tv channels list
[FreetuxTV]    INFO       : Loading the list of channels
[FreetuxTV]    INFO       : Loading the list of recordings
[FreetuxTV]    INFO       : DBSync close database
[FreetuxTV]    INFO       : Showing the main window, hide splashscreen
[FreetuxTV]    INFO       : Loading GtkBuilder object "dialogaddgroup" from /usr/local/share/freetuxtv/ui/addchannelsgroups.glade

** (freetuxtv:6746): CRITICAL **: gtk_builder_window_get_top_window: assertion 'GTK_IS_WINDOW(pObject)' failed

(freetuxtv:6746): Gtk-CRITICAL **: gtk_window_set_transient_for: assertion 'GTK_IS_WINDOW (window)' failed

(freetuxtv:6746): Gtk-CRITICAL **: gtk_window_set_position: assertion 'GTK_IS_WINDOW (window)' failed

(freetuxtv:6746): Gtk-CRITICAL **: gtk_tree_view_get_selection: assertion 'GTK_IS_TREE_VIEW (tree_view)' failed

(freetuxtv:6746): Gtk-CRITICAL **: gtk_tree_selection_set_mode: assertion 'GTK_IS_TREE_SELECTION (selection)' failed

(freetuxtv:6746): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:6746): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:6746): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:6746): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:6746): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(freetuxtv:6746): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(freetuxtv:6746): Gtk-CRITICAL **: gtk_tree_store_clear: assertion 'GTK_IS_TREE_STORE (tree_store)' failed
Segmentation fault (core dumped)

Tried to install from https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/multimedija but still no luck

**Comment by SaiyanRiku** [comment]
Look similar to issue fixed in 0.6.7. But you are using 0.6.6, you need the package to be updated.
