### ISSUE TITLE
libcurl4-openssl-dev conflicts with libssl1.0-dev

### ISSUE THREAD

**Issue by LogX7** [freetuxtv/freetuxtv#211]
i cannot build because i need to install libcurl4-openssl-dev  but it will remove libssl1.0-dev

**Comment by SaiyanRiku** [comment]
Hello, you can try with libcurl4-gnutls-dev, libcurl4-nss-dev, or maybe simply with libcurl-dev.

**Comment by LogX7** [comment]
@SaiyanRiku  libcurl4-nss-dev worked
