### ISSUE TITLE
tvg-logos from m3u-list not shown in freetuxtv

### ISSUE THREAD

**Issue by freddii** [freetuxtv/freetuxtv#216]
its possible to add tv stations just by urls like:
https://iptv-org.github.io/iptv/index.language.m3u
https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/kodi/kodi_tv.m3u
but the tv logos are not shown in freetuxtv.

I installed latest freetuxtv from ppa for ubuntu20.04.
for kodi_tv.m3u lot of icons are missing and it looks like this:
![kodinerds_missing_channels](https://user-images.githubusercontent.com/7213207/91097293-b6b7c580-e65f-11ea-8169-add518613fd5.png)

**Comment by SaiyanRiku** [comment]
Hi, not all icons are available. You can submit some new icons with a pull request and/or editing the file tv_channels.xml.
