### ISSUE TITLE
Synchronize TV channels database

### ISSUE THREAD

**Issue by muzena** [freetuxtv/freetuxtv#226]
@SaiyanRiku 
Why this option is disabled?
I try to sync [new playlist](https://raw.githubusercontent.com/muzena/freetuxtv/radio_playlists/croatian_radios.m3u) that I added.
Then I saw that tvchannelsdatabase.glade file missing and from /usr/share/freetuxtv/ui dir and from /usr/share/freetuxtv/ui/Makefile.am file.
I copied tvchannelsdatabase.glade file in from /usr/share/freetuxtv/ui dir, then I start sync.
In terminal output it seems that worked. downloading channel logos, syncing lists.
But this new playlist has one new radio station:
#EXTINF:1,Yammat FM
https://streaming.radio.co/s5ad4b474a/listen
which hasn't been added to freetuxtv in sync process.

**Comment by SaiyanRiku** [comment]
It wasn't supposed to be missing. I fixed it.
