### ISSUE TITLE
Contributing URLs to database.freetuxtv.net

### ISSUE THREAD

**Issue by NezbednikSK** [freetuxtv/freetuxtv#240]
So, I'm slovak. I found a few streams of slovak televisions (legal ofcourse) and I'd like to contribute them.
How would I go about submitting them?

**Comment by SaiyanRiku** [comment]
Please just submit them on http://database.freetuxtv.net

**Comment by NezbednikSK** [comment]
Oh, thanks! Didn't notice that textbox, ;-)
